type: object
description: Visual Novel configuration schema defining screen settings, UI tokens, components, story flow, and resources.
required:
  - screen
  - ui
  - resources
  - story
properties:
  screen:
    $ref: "./screen.schema.yaml"

  presets:
    type: object
    description: Placeholder for user-defined style or behavior presets.
    additionalProperties: true

  ui:
    type: object
    description: User Interface settings including design tokens and UI components.
    required:
      - designTokens
    properties:
      designTokens:
        $ref: "./designToken.schema.yaml"
      components:
        $ref: "./component.schema.yaml"

  resources:
    type: object
    description: Definitions of global resources used in the game (e.g. variables, backgrounds).
    required:
      - variables
      - backgrounds
    properties:
      variables:
        $ref: "./resources.schema.yaml#/variableSchema"
      backgrounds:
        $ref: "./resources.schema.yaml#/backgroundSchema"

  story:
    $ref: "./story.schema.yaml"
