export const RENDER_LAYER = Object.freeze({
  VISUAL_BEHIND_BACKGROUND: 10,
  BACKGROUND: 20,
  VISUAL_BEHIND_CHARACTER: 30,
  CHARACTER: 40,
  VISUAL_BEHIND_DIALOGUE: 50,
  DIALOGUE: 60,
  VISUAL_FOREGROUND: 70,
});

export const VISUAL_LAYER = Object.freeze({
  BEHIND_BACKGROUND: RENDER_LAYER.VISUAL_BEHIND_BACKGROUND,
  BEHIND_CHARACTER: RENDER_LAYER.VISUAL_BEHIND_CHARACTER,
  BEHIND_DIALOGUE: RENDER_LAYER.VISUAL_BEHIND_DIALOGUE,
  FOREGROUND: RENDER_LAYER.VISUAL_FOREGROUND,
});

export const DEFAULT_VISUAL_LAYER = VISUAL_LAYER.BEHIND_DIALOGUE;

export const VISUAL_LAYER_VALUES = Object.freeze(
  Object.values(VISUAL_LAYER).sort((left, right) => left - right),
);
